### ISSUE TITLE
引用插件后安卓调用闪退

### ISSUE THREAD

**Issue by wowtrxqn** [PoisonousMilkPowder/WeexPlugin-HMGesUnlock#2]
现在引用调设置解锁activity直接闪退

**Comment by PoisonousMilkPowder** [comment]
蛮久远了，都2020年了，才看到。尴尬
好久没碰weex了，当时这个插件也只是看看eros的自定义插件创建流程通不通，我自己的项目其实没有以插件的方式引入这个手势解锁。
哎，eros也不更新了。世事难料。
